[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npx -y pnpm@10.5.0 install --frozen-lockfile"]

[phases.build]
cmds = ["npx -y pnpm@10.5.0 db:generate", "npx -y pnpm@10.5.0 build"]

[start]
cmd = "npx -y pnpm@10.5.0 start"
